coverage:
  paths:
    - coverage/lcov.info
  exclude:
    - Tests/**/*.swift
    - .build/**
  badge:
    path: docs/coverage.svg
codeToTestRatio:
  code:
    - Sources/**/*.swift
  test:
    - Tests/**/*.swift
  badge:
    path: docs/ratio.svg
testExecutionTime:
  if: true
  badge:
    path: docs/time.svg
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
summary:
  if: true
push:
  if: is_default_branch
