// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import AppleProductTypes
import PackageDescription

let package = Package(
  name: "Example",
  platforms: [
    .iOS("18.0")
  ],
  products: [
    .iOSApplication(
      name: "Example",
      targets: ["AppModule"],
      bundleIdentifier: "dev.to4iki.Store.Example",
      displayVersion: "1.0",
      bundleVersion: "1",
      appIcon: .placeholder(icon: .earth),
      accentColor: .presetColor(.blue),
      supportedDeviceFamilies: [
        .pad,
        .phone,
      ],
      supportedInterfaceOrientations: [
        .portrait,
        .landscapeRight,
        .landscapeLeft,
        .portraitUpsideDown(.when(deviceFamilies: [.pad])),
      ]
    )
  ],
  dependencies: [
    .package(path: "../Store")
  ],
  targets: [
    .executableTarget(
      name: "AppModule",
      dependencies: [
        .product(name: "Store", package: "store")
      ],
      path: "."
    )
  ],
  swiftLanguageVersions: [.version("6")]
)
