name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      pull-requests: write
      actions: write
    steps:
      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: "6.2"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests with coverage
        run: make coverage
      - name: Run octocov
        uses: k1LoW/octocov-action@v1
